// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

/**
 * Protobuf type {@code emqx.exhook.v2.BrokerInfo}
 */
public final class BrokerInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v2.BrokerInfo)
        BrokerInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BrokerInfo.newBuilder() to construct.
  private BrokerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BrokerInfo() {
    version_ = "";
    sysdescr_ = "";
    datetime_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new BrokerInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_BrokerInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_BrokerInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.emqx.exhook.BrokerInfo.class, io.emqx.exhook.BrokerInfo.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private volatile Object version_;
  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  @Override
  public String getVersion() {
    Object ref = version_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  @Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    Object ref = version_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSDESCR_FIELD_NUMBER = 2;
  private volatile Object sysdescr_;
  /**
   * <code>string sysdescr = 2;</code>
   * @return The sysdescr.
   */
  @Override
  public String getSysdescr() {
    Object ref = sysdescr_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sysdescr_ = s;
      return s;
    }
  }
  /**
   * <code>string sysdescr = 2;</code>
   * @return The bytes for sysdescr.
   */
  @Override
  public com.google.protobuf.ByteString
      getSysdescrBytes() {
    Object ref = sysdescr_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sysdescr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPTIME_FIELD_NUMBER = 3;
  private long uptime_;
  /**
   * <code>int64 uptime = 3;</code>
   * @return The uptime.
   */
  @Override
  public long getUptime() {
    return uptime_;
  }

  public static final int DATETIME_FIELD_NUMBER = 4;
  private volatile Object datetime_;
  /**
   * <code>string datetime = 4;</code>
   * @return The datetime.
   */
  @Override
  public String getDatetime() {
    Object ref = datetime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      datetime_ = s;
      return s;
    }
  }
  /**
   * <code>string datetime = 4;</code>
   * @return The bytes for datetime.
   */
  @Override
  public com.google.protobuf.ByteString
      getDatetimeBytes() {
    Object ref = datetime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      datetime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sysdescr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sysdescr_);
    }
    if (uptime_ != 0L) {
      output.writeInt64(3, uptime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datetime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, datetime_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sysdescr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sysdescr_);
    }
    if (uptime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, uptime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datetime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, datetime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.emqx.exhook.BrokerInfo)) {
      return super.equals(obj);
    }
    io.emqx.exhook.BrokerInfo other = (io.emqx.exhook.BrokerInfo) obj;

    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getSysdescr()
        .equals(other.getSysdescr())) return false;
    if (getUptime()
        != other.getUptime()) return false;
    if (!getDatetime()
        .equals(other.getDatetime())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + SYSDESCR_FIELD_NUMBER;
    hash = (53 * hash) + getSysdescr().hashCode();
    hash = (37 * hash) + UPTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUptime());
    hash = (37 * hash) + DATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getDatetime().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.emqx.exhook.BrokerInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.BrokerInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.BrokerInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.BrokerInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.emqx.exhook.BrokerInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v2.BrokerInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v2.BrokerInfo)
      BrokerInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_BrokerInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_BrokerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.emqx.exhook.BrokerInfo.class, io.emqx.exhook.BrokerInfo.Builder.class);
    }

    // Construct using io.emqx.exhook.BrokerInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      version_ = "";

      sysdescr_ = "";

      uptime_ = 0L;

      datetime_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_BrokerInfo_descriptor;
    }

    @Override
    public io.emqx.exhook.BrokerInfo getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public io.emqx.exhook.BrokerInfo build() {
      io.emqx.exhook.BrokerInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public io.emqx.exhook.BrokerInfo buildPartial() {
      io.emqx.exhook.BrokerInfo result = new io.emqx.exhook.BrokerInfo(this);
      result.version_ = version_;
      result.sysdescr_ = sysdescr_;
      result.uptime_ = uptime_;
      result.datetime_ = datetime_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.emqx.exhook.BrokerInfo) {
        return mergeFrom((io.emqx.exhook.BrokerInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.emqx.exhook.BrokerInfo other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (!other.getSysdescr().isEmpty()) {
        sysdescr_ = other.sysdescr_;
        onChanged();
      }
      if (other.getUptime() != 0L) {
        setUptime(other.getUptime());
      }
      if (!other.getDatetime().isEmpty()) {
        datetime_ = other.datetime_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              version_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              sysdescr_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              uptime_ = input.readInt64();

              break;
            } // case 24
            case 34: {
              datetime_ = input.readStringRequireUtf8();

              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private Object version_ = "";
    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    public String getVersion() {
      Object ref = version_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private Object sysdescr_ = "";
    /**
     * <code>string sysdescr = 2;</code>
     * @return The sysdescr.
     */
    public String getSysdescr() {
      Object ref = sysdescr_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sysdescr_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sysdescr = 2;</code>
     * @return The bytes for sysdescr.
     */
    public com.google.protobuf.ByteString
        getSysdescrBytes() {
      Object ref = sysdescr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sysdescr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sysdescr = 2;</code>
     * @param value The sysdescr to set.
     * @return This builder for chaining.
     */
    public Builder setSysdescr(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sysdescr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sysdescr = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSysdescr() {
      
      sysdescr_ = getDefaultInstance().getSysdescr();
      onChanged();
      return this;
    }
    /**
     * <code>string sysdescr = 2;</code>
     * @param value The bytes for sysdescr to set.
     * @return This builder for chaining.
     */
    public Builder setSysdescrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sysdescr_ = value;
      onChanged();
      return this;
    }

    private long uptime_ ;
    /**
     * <code>int64 uptime = 3;</code>
     * @return The uptime.
     */
    @Override
    public long getUptime() {
      return uptime_;
    }
    /**
     * <code>int64 uptime = 3;</code>
     * @param value The uptime to set.
     * @return This builder for chaining.
     */
    public Builder setUptime(long value) {
      
      uptime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 uptime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUptime() {
      
      uptime_ = 0L;
      onChanged();
      return this;
    }

    private Object datetime_ = "";
    /**
     * <code>string datetime = 4;</code>
     * @return The datetime.
     */
    public String getDatetime() {
      Object ref = datetime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        datetime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string datetime = 4;</code>
     * @return The bytes for datetime.
     */
    public com.google.protobuf.ByteString
        getDatetimeBytes() {
      Object ref = datetime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        datetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string datetime = 4;</code>
     * @param value The datetime to set.
     * @return This builder for chaining.
     */
    public Builder setDatetime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datetime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string datetime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatetime() {
      
      datetime_ = getDefaultInstance().getDatetime();
      onChanged();
      return this;
    }
    /**
     * <code>string datetime = 4;</code>
     * @param value The bytes for datetime to set.
     * @return This builder for chaining.
     */
    public Builder setDatetimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datetime_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v2.BrokerInfo)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v2.BrokerInfo)
  private static final io.emqx.exhook.BrokerInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.emqx.exhook.BrokerInfo();
  }

  public static io.emqx.exhook.BrokerInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BrokerInfo>
      PARSER = new com.google.protobuf.AbstractParser<BrokerInfo>() {
    @Override
    public BrokerInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BrokerInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BrokerInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public io.emqx.exhook.BrokerInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

