// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

/**
 * Protobuf type {@code emqx.exhook.v2.ClientSubscribeRequest}
 */
public final class ClientSubscribeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v2.ClientSubscribeRequest)
        ClientSubscribeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientSubscribeRequest.newBuilder() to construct.
  private ClientSubscribeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientSubscribeRequest() {
    props_ = java.util.Collections.emptyList();
    topicFilters_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientSubscribeRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientSubscribeRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientSubscribeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.emqx.exhook.ClientSubscribeRequest.class, io.emqx.exhook.ClientSubscribeRequest.Builder.class);
  }

  public static final int CLIENTINFO_FIELD_NUMBER = 1;
  private io.emqx.exhook.ClientInfo clientinfo_;
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   * @return Whether the clientinfo field is set.
   */
  @Override
  public boolean hasClientinfo() {
    return clientinfo_ != null;
  }
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   * @return The clientinfo.
   */
  @Override
  public io.emqx.exhook.ClientInfo getClientinfo() {
    return clientinfo_ == null ? io.emqx.exhook.ClientInfo.getDefaultInstance() : clientinfo_;
  }
  /**
   * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
   */
  @Override
  public io.emqx.exhook.ClientInfoOrBuilder getClientinfoOrBuilder() {
    return getClientinfo();
  }

  public static final int PROPS_FIELD_NUMBER = 2;
  private java.util.List<io.emqx.exhook.Property> props_;
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  @Override
  public java.util.List<io.emqx.exhook.Property> getPropsList() {
    return props_;
  }
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  @Override
  public java.util.List<? extends io.emqx.exhook.PropertyOrBuilder> 
      getPropsOrBuilderList() {
    return props_;
  }
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  @Override
  public int getPropsCount() {
    return props_.size();
  }
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  @Override
  public io.emqx.exhook.Property getProps(int index) {
    return props_.get(index);
  }
  /**
   * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
   */
  @Override
  public io.emqx.exhook.PropertyOrBuilder getPropsOrBuilder(
      int index) {
    return props_.get(index);
  }

  public static final int TOPIC_FILTERS_FIELD_NUMBER = 3;
  private java.util.List<io.emqx.exhook.TopicFilter> topicFilters_;
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  @Override
  public java.util.List<io.emqx.exhook.TopicFilter> getTopicFiltersList() {
    return topicFilters_;
  }
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  @Override
  public java.util.List<? extends io.emqx.exhook.TopicFilterOrBuilder> 
      getTopicFiltersOrBuilderList() {
    return topicFilters_;
  }
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  @Override
  public int getTopicFiltersCount() {
    return topicFilters_.size();
  }
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  @Override
  public io.emqx.exhook.TopicFilter getTopicFilters(int index) {
    return topicFilters_.get(index);
  }
  /**
   * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
   */
  @Override
  public io.emqx.exhook.TopicFilterOrBuilder getTopicFiltersOrBuilder(
      int index) {
    return topicFilters_.get(index);
  }

  public static final int META_FIELD_NUMBER = 4;
  private io.emqx.exhook.RequestMeta meta_;
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   * @return Whether the meta field is set.
   */
  @Override
  public boolean hasMeta() {
    return meta_ != null;
  }
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   * @return The meta.
   */
  @Override
  public io.emqx.exhook.RequestMeta getMeta() {
    return meta_ == null ? io.emqx.exhook.RequestMeta.getDefaultInstance() : meta_;
  }
  /**
   * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
   */
  @Override
  public io.emqx.exhook.RequestMetaOrBuilder getMetaOrBuilder() {
    return getMeta();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (clientinfo_ != null) {
      output.writeMessage(1, getClientinfo());
    }
    for (int i = 0; i < props_.size(); i++) {
      output.writeMessage(2, props_.get(i));
    }
    for (int i = 0; i < topicFilters_.size(); i++) {
      output.writeMessage(3, topicFilters_.get(i));
    }
    if (meta_ != null) {
      output.writeMessage(4, getMeta());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (clientinfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getClientinfo());
    }
    for (int i = 0; i < props_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, props_.get(i));
    }
    for (int i = 0; i < topicFilters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, topicFilters_.get(i));
    }
    if (meta_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMeta());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.emqx.exhook.ClientSubscribeRequest)) {
      return super.equals(obj);
    }
    io.emqx.exhook.ClientSubscribeRequest other = (io.emqx.exhook.ClientSubscribeRequest) obj;

    if (hasClientinfo() != other.hasClientinfo()) return false;
    if (hasClientinfo()) {
      if (!getClientinfo()
          .equals(other.getClientinfo())) return false;
    }
    if (!getPropsList()
        .equals(other.getPropsList())) return false;
    if (!getTopicFiltersList()
        .equals(other.getTopicFiltersList())) return false;
    if (hasMeta() != other.hasMeta()) return false;
    if (hasMeta()) {
      if (!getMeta()
          .equals(other.getMeta())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasClientinfo()) {
      hash = (37 * hash) + CLIENTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getClientinfo().hashCode();
    }
    if (getPropsCount() > 0) {
      hash = (37 * hash) + PROPS_FIELD_NUMBER;
      hash = (53 * hash) + getPropsList().hashCode();
    }
    if (getTopicFiltersCount() > 0) {
      hash = (37 * hash) + TOPIC_FILTERS_FIELD_NUMBER;
      hash = (53 * hash) + getTopicFiltersList().hashCode();
    }
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientSubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.emqx.exhook.ClientSubscribeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v2.ClientSubscribeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v2.ClientSubscribeRequest)
      ClientSubscribeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientSubscribeRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientSubscribeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.emqx.exhook.ClientSubscribeRequest.class, io.emqx.exhook.ClientSubscribeRequest.Builder.class);
    }

    // Construct using io.emqx.exhook.ClientSubscribeRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      if (clientinfoBuilder_ == null) {
        clientinfo_ = null;
      } else {
        clientinfo_ = null;
        clientinfoBuilder_ = null;
      }
      if (propsBuilder_ == null) {
        props_ = java.util.Collections.emptyList();
      } else {
        props_ = null;
        propsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (topicFiltersBuilder_ == null) {
        topicFilters_ = java.util.Collections.emptyList();
      } else {
        topicFilters_ = null;
        topicFiltersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (metaBuilder_ == null) {
        meta_ = null;
      } else {
        meta_ = null;
        metaBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientSubscribeRequest_descriptor;
    }

    @Override
    public io.emqx.exhook.ClientSubscribeRequest getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public io.emqx.exhook.ClientSubscribeRequest build() {
      io.emqx.exhook.ClientSubscribeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public io.emqx.exhook.ClientSubscribeRequest buildPartial() {
      io.emqx.exhook.ClientSubscribeRequest result = new io.emqx.exhook.ClientSubscribeRequest(this);
      int from_bitField0_ = bitField0_;
      if (clientinfoBuilder_ == null) {
        result.clientinfo_ = clientinfo_;
      } else {
        result.clientinfo_ = clientinfoBuilder_.build();
      }
      if (propsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          props_ = java.util.Collections.unmodifiableList(props_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.props_ = props_;
      } else {
        result.props_ = propsBuilder_.build();
      }
      if (topicFiltersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          topicFilters_ = java.util.Collections.unmodifiableList(topicFilters_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.topicFilters_ = topicFilters_;
      } else {
        result.topicFilters_ = topicFiltersBuilder_.build();
      }
      if (metaBuilder_ == null) {
        result.meta_ = meta_;
      } else {
        result.meta_ = metaBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.emqx.exhook.ClientSubscribeRequest) {
        return mergeFrom((io.emqx.exhook.ClientSubscribeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.emqx.exhook.ClientSubscribeRequest other) {
      if (other == getDefaultInstance()) return this;
      if (other.hasClientinfo()) {
        mergeClientinfo(other.getClientinfo());
      }
      if (propsBuilder_ == null) {
        if (!other.props_.isEmpty()) {
          if (props_.isEmpty()) {
            props_ = other.props_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePropsIsMutable();
            props_.addAll(other.props_);
          }
          onChanged();
        }
      } else {
        if (!other.props_.isEmpty()) {
          if (propsBuilder_.isEmpty()) {
            propsBuilder_.dispose();
            propsBuilder_ = null;
            props_ = other.props_;
            bitField0_ = (bitField0_ & ~0x00000001);
            propsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPropsFieldBuilder() : null;
          } else {
            propsBuilder_.addAllMessages(other.props_);
          }
        }
      }
      if (topicFiltersBuilder_ == null) {
        if (!other.topicFilters_.isEmpty()) {
          if (topicFilters_.isEmpty()) {
            topicFilters_ = other.topicFilters_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTopicFiltersIsMutable();
            topicFilters_.addAll(other.topicFilters_);
          }
          onChanged();
        }
      } else {
        if (!other.topicFilters_.isEmpty()) {
          if (topicFiltersBuilder_.isEmpty()) {
            topicFiltersBuilder_.dispose();
            topicFiltersBuilder_ = null;
            topicFilters_ = other.topicFilters_;
            bitField0_ = (bitField0_ & ~0x00000002);
            topicFiltersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTopicFiltersFieldBuilder() : null;
          } else {
            topicFiltersBuilder_.addAllMessages(other.topicFilters_);
          }
        }
      }
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getClientinfoFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              io.emqx.exhook.Property m =
                  input.readMessage(
                      io.emqx.exhook.Property.parser(),
                      extensionRegistry);
              if (propsBuilder_ == null) {
                ensurePropsIsMutable();
                props_.add(m);
              } else {
                propsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              io.emqx.exhook.TopicFilter m =
                  input.readMessage(
                      io.emqx.exhook.TopicFilter.parser(),
                      extensionRegistry);
              if (topicFiltersBuilder_ == null) {
                ensureTopicFiltersIsMutable();
                topicFilters_.add(m);
              } else {
                topicFiltersBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getMetaFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.emqx.exhook.ClientInfo clientinfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.emqx.exhook.ClientInfo, io.emqx.exhook.ClientInfo.Builder, io.emqx.exhook.ClientInfoOrBuilder> clientinfoBuilder_;
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     * @return Whether the clientinfo field is set.
     */
    public boolean hasClientinfo() {
      return clientinfoBuilder_ != null || clientinfo_ != null;
    }
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     * @return The clientinfo.
     */
    public io.emqx.exhook.ClientInfo getClientinfo() {
      if (clientinfoBuilder_ == null) {
        return clientinfo_ == null ? io.emqx.exhook.ClientInfo.getDefaultInstance() : clientinfo_;
      } else {
        return clientinfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     */
    public Builder setClientinfo(io.emqx.exhook.ClientInfo value) {
      if (clientinfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientinfo_ = value;
        onChanged();
      } else {
        clientinfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     */
    public Builder setClientinfo(
        io.emqx.exhook.ClientInfo.Builder builderForValue) {
      if (clientinfoBuilder_ == null) {
        clientinfo_ = builderForValue.build();
        onChanged();
      } else {
        clientinfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     */
    public Builder mergeClientinfo(io.emqx.exhook.ClientInfo value) {
      if (clientinfoBuilder_ == null) {
        if (clientinfo_ != null) {
          clientinfo_ =
            io.emqx.exhook.ClientInfo.newBuilder(clientinfo_).mergeFrom(value).buildPartial();
        } else {
          clientinfo_ = value;
        }
        onChanged();
      } else {
        clientinfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     */
    public Builder clearClientinfo() {
      if (clientinfoBuilder_ == null) {
        clientinfo_ = null;
        onChanged();
      } else {
        clientinfo_ = null;
        clientinfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     */
    public io.emqx.exhook.ClientInfo.Builder getClientinfoBuilder() {
      
      onChanged();
      return getClientinfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     */
    public io.emqx.exhook.ClientInfoOrBuilder getClientinfoOrBuilder() {
      if (clientinfoBuilder_ != null) {
        return clientinfoBuilder_.getMessageOrBuilder();
      } else {
        return clientinfo_ == null ?
            io.emqx.exhook.ClientInfo.getDefaultInstance() : clientinfo_;
      }
    }
    /**
     * <code>.emqx.exhook.v2.ClientInfo clientinfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.emqx.exhook.ClientInfo, io.emqx.exhook.ClientInfo.Builder, io.emqx.exhook.ClientInfoOrBuilder> 
        getClientinfoFieldBuilder() {
      if (clientinfoBuilder_ == null) {
        clientinfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.emqx.exhook.ClientInfo, io.emqx.exhook.ClientInfo.Builder, io.emqx.exhook.ClientInfoOrBuilder>(
                getClientinfo(),
                getParentForChildren(),
                isClean());
        clientinfo_ = null;
      }
      return clientinfoBuilder_;
    }

    private java.util.List<io.emqx.exhook.Property> props_ =
      java.util.Collections.emptyList();
    private void ensurePropsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        props_ = new java.util.ArrayList<io.emqx.exhook.Property>(props_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.Property, io.emqx.exhook.Property.Builder, io.emqx.exhook.PropertyOrBuilder> propsBuilder_;

    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public java.util.List<io.emqx.exhook.Property> getPropsList() {
      if (propsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(props_);
      } else {
        return propsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public int getPropsCount() {
      if (propsBuilder_ == null) {
        return props_.size();
      } else {
        return propsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public io.emqx.exhook.Property getProps(int index) {
      if (propsBuilder_ == null) {
        return props_.get(index);
      } else {
        return propsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder setProps(
        int index, io.emqx.exhook.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.set(index, value);
        onChanged();
      } else {
        propsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder setProps(
        int index, io.emqx.exhook.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.set(index, builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder addProps(io.emqx.exhook.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.add(value);
        onChanged();
      } else {
        propsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder addProps(
        int index, io.emqx.exhook.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.add(index, value);
        onChanged();
      } else {
        propsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder addProps(
        io.emqx.exhook.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.add(builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder addProps(
        int index, io.emqx.exhook.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.add(index, builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder addAllProps(
        Iterable<? extends io.emqx.exhook.Property> values) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, props_);
        onChanged();
      } else {
        propsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder clearProps() {
      if (propsBuilder_ == null) {
        props_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        propsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public Builder removeProps(int index) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.remove(index);
        onChanged();
      } else {
        propsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public io.emqx.exhook.Property.Builder getPropsBuilder(
        int index) {
      return getPropsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public io.emqx.exhook.PropertyOrBuilder getPropsOrBuilder(
        int index) {
      if (propsBuilder_ == null) {
        return props_.get(index);  } else {
        return propsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public java.util.List<? extends io.emqx.exhook.PropertyOrBuilder> 
         getPropsOrBuilderList() {
      if (propsBuilder_ != null) {
        return propsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(props_);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public io.emqx.exhook.Property.Builder addPropsBuilder() {
      return getPropsFieldBuilder().addBuilder(
          io.emqx.exhook.Property.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public io.emqx.exhook.Property.Builder addPropsBuilder(
        int index) {
      return getPropsFieldBuilder().addBuilder(
          index, io.emqx.exhook.Property.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v2.Property props = 2;</code>
     */
    public java.util.List<io.emqx.exhook.Property.Builder> 
         getPropsBuilderList() {
      return getPropsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.Property, io.emqx.exhook.Property.Builder, io.emqx.exhook.PropertyOrBuilder> 
        getPropsFieldBuilder() {
      if (propsBuilder_ == null) {
        propsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.emqx.exhook.Property, io.emqx.exhook.Property.Builder, io.emqx.exhook.PropertyOrBuilder>(
                props_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        props_ = null;
      }
      return propsBuilder_;
    }

    private java.util.List<io.emqx.exhook.TopicFilter> topicFilters_ =
      java.util.Collections.emptyList();
    private void ensureTopicFiltersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        topicFilters_ = new java.util.ArrayList<io.emqx.exhook.TopicFilter>(topicFilters_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.TopicFilter, io.emqx.exhook.TopicFilter.Builder, io.emqx.exhook.TopicFilterOrBuilder> topicFiltersBuilder_;

    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public java.util.List<io.emqx.exhook.TopicFilter> getTopicFiltersList() {
      if (topicFiltersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(topicFilters_);
      } else {
        return topicFiltersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public int getTopicFiltersCount() {
      if (topicFiltersBuilder_ == null) {
        return topicFilters_.size();
      } else {
        return topicFiltersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilter getTopicFilters(int index) {
      if (topicFiltersBuilder_ == null) {
        return topicFilters_.get(index);
      } else {
        return topicFiltersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder setTopicFilters(
        int index, io.emqx.exhook.TopicFilter value) {
      if (topicFiltersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicFiltersIsMutable();
        topicFilters_.set(index, value);
        onChanged();
      } else {
        topicFiltersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder setTopicFilters(
        int index, io.emqx.exhook.TopicFilter.Builder builderForValue) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        topicFilters_.set(index, builderForValue.build());
        onChanged();
      } else {
        topicFiltersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder addTopicFilters(io.emqx.exhook.TopicFilter value) {
      if (topicFiltersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicFiltersIsMutable();
        topicFilters_.add(value);
        onChanged();
      } else {
        topicFiltersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder addTopicFilters(
        int index, io.emqx.exhook.TopicFilter value) {
      if (topicFiltersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicFiltersIsMutable();
        topicFilters_.add(index, value);
        onChanged();
      } else {
        topicFiltersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder addTopicFilters(
        io.emqx.exhook.TopicFilter.Builder builderForValue) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        topicFilters_.add(builderForValue.build());
        onChanged();
      } else {
        topicFiltersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder addTopicFilters(
        int index, io.emqx.exhook.TopicFilter.Builder builderForValue) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        topicFilters_.add(index, builderForValue.build());
        onChanged();
      } else {
        topicFiltersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder addAllTopicFilters(
        Iterable<? extends io.emqx.exhook.TopicFilter> values) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        addAll(
            values, topicFilters_);
        onChanged();
      } else {
        topicFiltersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder clearTopicFilters() {
      if (topicFiltersBuilder_ == null) {
        topicFilters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        topicFiltersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public Builder removeTopicFilters(int index) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        topicFilters_.remove(index);
        onChanged();
      } else {
        topicFiltersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilter.Builder getTopicFiltersBuilder(
        int index) {
      return getTopicFiltersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilterOrBuilder getTopicFiltersOrBuilder(
        int index) {
      if (topicFiltersBuilder_ == null) {
        return topicFilters_.get(index);  } else {
        return topicFiltersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public java.util.List<? extends io.emqx.exhook.TopicFilterOrBuilder> 
         getTopicFiltersOrBuilderList() {
      if (topicFiltersBuilder_ != null) {
        return topicFiltersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(topicFilters_);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilter.Builder addTopicFiltersBuilder() {
      return getTopicFiltersFieldBuilder().addBuilder(
          io.emqx.exhook.TopicFilter.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilter.Builder addTopicFiltersBuilder(
        int index) {
      return getTopicFiltersFieldBuilder().addBuilder(
          index, io.emqx.exhook.TopicFilter.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v2.TopicFilter topic_filters = 3;</code>
     */
    public java.util.List<io.emqx.exhook.TopicFilter.Builder> 
         getTopicFiltersBuilderList() {
      return getTopicFiltersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.TopicFilter, io.emqx.exhook.TopicFilter.Builder, io.emqx.exhook.TopicFilterOrBuilder> 
        getTopicFiltersFieldBuilder() {
      if (topicFiltersBuilder_ == null) {
        topicFiltersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.emqx.exhook.TopicFilter, io.emqx.exhook.TopicFilter.Builder, io.emqx.exhook.TopicFilterOrBuilder>(
                topicFilters_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        topicFilters_ = null;
      }
      return topicFiltersBuilder_;
    }

    private io.emqx.exhook.RequestMeta meta_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.emqx.exhook.RequestMeta, io.emqx.exhook.RequestMeta.Builder, io.emqx.exhook.RequestMetaOrBuilder> metaBuilder_;
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     * @return Whether the meta field is set.
     */
    public boolean hasMeta() {
      return metaBuilder_ != null || meta_ != null;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     * @return The meta.
     */
    public io.emqx.exhook.RequestMeta getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? io.emqx.exhook.RequestMeta.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public Builder setMeta(io.emqx.exhook.RequestMeta value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
        onChanged();
      } else {
        metaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public Builder setMeta(
        io.emqx.exhook.RequestMeta.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
        onChanged();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public Builder mergeMeta(io.emqx.exhook.RequestMeta value) {
      if (metaBuilder_ == null) {
        if (meta_ != null) {
          meta_ =
            io.emqx.exhook.RequestMeta.newBuilder(meta_).mergeFrom(value).buildPartial();
        } else {
          meta_ = value;
        }
        onChanged();
      } else {
        metaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public Builder clearMeta() {
      if (metaBuilder_ == null) {
        meta_ = null;
        onChanged();
      } else {
        meta_ = null;
        metaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public io.emqx.exhook.RequestMeta.Builder getMetaBuilder() {
      
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    public io.emqx.exhook.RequestMetaOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            io.emqx.exhook.RequestMeta.getDefaultInstance() : meta_;
      }
    }
    /**
     * <code>.emqx.exhook.v2.RequestMeta meta = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.emqx.exhook.RequestMeta, io.emqx.exhook.RequestMeta.Builder, io.emqx.exhook.RequestMetaOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.emqx.exhook.RequestMeta, io.emqx.exhook.RequestMeta.Builder, io.emqx.exhook.RequestMetaOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v2.ClientSubscribeRequest)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v2.ClientSubscribeRequest)
  private static final io.emqx.exhook.ClientSubscribeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.emqx.exhook.ClientSubscribeRequest();
  }

  public static io.emqx.exhook.ClientSubscribeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientSubscribeRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClientSubscribeRequest>() {
    @Override
    public ClientSubscribeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientSubscribeRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ClientSubscribeRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public io.emqx.exhook.ClientSubscribeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

