// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

/**
 * Protobuf type {@code emqx.exhook.v2.ClientInfo}
 */
public final class ClientInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v2.ClientInfo)
        ClientInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientInfo.newBuilder() to construct.
  private ClientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientInfo() {
    node_ = "";
    clientid_ = "";
    username_ = "";
    password_ = "";
    peerhost_ = "";
    protocol_ = "";
    mountpoint_ = "";
    cn_ = "";
    dn_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.emqx.exhook.ClientInfo.class, io.emqx.exhook.ClientInfo.Builder.class);
  }

  public static final int NODE_FIELD_NUMBER = 1;
  private volatile Object node_;
  /**
   * <code>string node = 1;</code>
   * @return The node.
   */
  @Override
  public String getNode() {
    Object ref = node_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      node_ = s;
      return s;
    }
  }
  /**
   * <code>string node = 1;</code>
   * @return The bytes for node.
   */
  @Override
  public com.google.protobuf.ByteString
      getNodeBytes() {
    Object ref = node_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      node_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private volatile Object clientid_;
  /**
   * <code>string clientid = 2;</code>
   * @return The clientid.
   */
  @Override
  public String getClientid() {
    Object ref = clientid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      clientid_ = s;
      return s;
    }
  }
  /**
   * <code>string clientid = 2;</code>
   * @return The bytes for clientid.
   */
  @Override
  public com.google.protobuf.ByteString
      getClientidBytes() {
    Object ref = clientid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      clientid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 3;
  private volatile Object username_;
  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  @Override
  public String getUsername() {
    Object ref = username_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  @Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    Object ref = username_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 4;
  private volatile Object password_;
  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  @Override
  public String getPassword() {
    Object ref = password_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  @Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    Object ref = password_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEERHOST_FIELD_NUMBER = 5;
  private volatile Object peerhost_;
  /**
   * <code>string peerhost = 5;</code>
   * @return The peerhost.
   */
  @Override
  public String getPeerhost() {
    Object ref = peerhost_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      peerhost_ = s;
      return s;
    }
  }
  /**
   * <code>string peerhost = 5;</code>
   * @return The bytes for peerhost.
   */
  @Override
  public com.google.protobuf.ByteString
      getPeerhostBytes() {
    Object ref = peerhost_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      peerhost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOCKPORT_FIELD_NUMBER = 6;
  private int sockport_;
  /**
   * <code>uint32 sockport = 6;</code>
   * @return The sockport.
   */
  @Override
  public int getSockport() {
    return sockport_;
  }

  public static final int PROTOCOL_FIELD_NUMBER = 7;
  private volatile Object protocol_;
  /**
   * <code>string protocol = 7;</code>
   * @return The protocol.
   */
  @Override
  public String getProtocol() {
    Object ref = protocol_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      protocol_ = s;
      return s;
    }
  }
  /**
   * <code>string protocol = 7;</code>
   * @return The bytes for protocol.
   */
  @Override
  public com.google.protobuf.ByteString
      getProtocolBytes() {
    Object ref = protocol_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      protocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOUNTPOINT_FIELD_NUMBER = 8;
  private volatile Object mountpoint_;
  /**
   * <code>string mountpoint = 8;</code>
   * @return The mountpoint.
   */
  @Override
  public String getMountpoint() {
    Object ref = mountpoint_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      mountpoint_ = s;
      return s;
    }
  }
  /**
   * <code>string mountpoint = 8;</code>
   * @return The bytes for mountpoint.
   */
  @Override
  public com.google.protobuf.ByteString
      getMountpointBytes() {
    Object ref = mountpoint_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      mountpoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_SUPERUSER_FIELD_NUMBER = 9;
  private boolean isSuperuser_;
  /**
   * <code>bool is_superuser = 9;</code>
   * @return The isSuperuser.
   */
  @Override
  public boolean getIsSuperuser() {
    return isSuperuser_;
  }

  public static final int ANONYMOUS_FIELD_NUMBER = 10;
  private boolean anonymous_;
  /**
   * <code>bool anonymous = 10;</code>
   * @return The anonymous.
   */
  @Override
  public boolean getAnonymous() {
    return anonymous_;
  }

  public static final int CN_FIELD_NUMBER = 11;
  private volatile Object cn_;
  /**
   * <pre>
   * common name of client TLS cert
   * </pre>
   *
   * <code>string cn = 11;</code>
   * @return The cn.
   */
  @Override
  public String getCn() {
    Object ref = cn_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * common name of client TLS cert
   * </pre>
   *
   * <code>string cn = 11;</code>
   * @return The bytes for cn.
   */
  @Override
  public com.google.protobuf.ByteString
      getCnBytes() {
    Object ref = cn_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DN_FIELD_NUMBER = 12;
  private volatile Object dn_;
  /**
   * <pre>
   * subject of client TLS cert
   * </pre>
   *
   * <code>string dn = 12;</code>
   * @return The dn.
   */
  @Override
  public String getDn() {
    Object ref = dn_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * subject of client TLS cert
   * </pre>
   *
   * <code>string dn = 12;</code>
   * @return The bytes for dn.
   */
  @Override
  public com.google.protobuf.ByteString
      getDnBytes() {
    Object ref = dn_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(node_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, node_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerhost_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, peerhost_);
    }
    if (sockport_ != 0) {
      output.writeUInt32(6, sockport_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protocol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mountpoint_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, mountpoint_);
    }
    if (isSuperuser_ != false) {
      output.writeBool(9, isSuperuser_);
    }
    if (anonymous_ != false) {
      output.writeBool(10, anonymous_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cn_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, cn_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dn_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, dn_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(node_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, node_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerhost_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, peerhost_);
    }
    if (sockport_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, sockport_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protocol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mountpoint_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, mountpoint_);
    }
    if (isSuperuser_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isSuperuser_);
    }
    if (anonymous_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, anonymous_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cn_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, cn_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dn_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, dn_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.emqx.exhook.ClientInfo)) {
      return super.equals(obj);
    }
    io.emqx.exhook.ClientInfo other = (io.emqx.exhook.ClientInfo) obj;

    if (!getNode()
        .equals(other.getNode())) return false;
    if (!getClientid()
        .equals(other.getClientid())) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getPeerhost()
        .equals(other.getPeerhost())) return false;
    if (getSockport()
        != other.getSockport()) return false;
    if (!getProtocol()
        .equals(other.getProtocol())) return false;
    if (!getMountpoint()
        .equals(other.getMountpoint())) return false;
    if (getIsSuperuser()
        != other.getIsSuperuser()) return false;
    if (getAnonymous()
        != other.getAnonymous()) return false;
    if (!getCn()
        .equals(other.getCn())) return false;
    if (!getDn()
        .equals(other.getDn())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODE_FIELD_NUMBER;
    hash = (53 * hash) + getNode().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientid().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + PEERHOST_FIELD_NUMBER;
    hash = (53 * hash) + getPeerhost().hashCode();
    hash = (37 * hash) + SOCKPORT_FIELD_NUMBER;
    hash = (53 * hash) + getSockport();
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getProtocol().hashCode();
    hash = (37 * hash) + MOUNTPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getMountpoint().hashCode();
    hash = (37 * hash) + IS_SUPERUSER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSuperuser());
    hash = (37 * hash) + ANONYMOUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAnonymous());
    hash = (37 * hash) + CN_FIELD_NUMBER;
    hash = (53 * hash) + getCn().hashCode();
    hash = (37 * hash) + DN_FIELD_NUMBER;
    hash = (53 * hash) + getDn().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.emqx.exhook.ClientInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ClientInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.emqx.exhook.ClientInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v2.ClientInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v2.ClientInfo)
      ClientInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.emqx.exhook.ClientInfo.class, io.emqx.exhook.ClientInfo.Builder.class);
    }

    // Construct using io.emqx.exhook.ClientInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      node_ = "";

      clientid_ = "";

      username_ = "";

      password_ = "";

      peerhost_ = "";

      sockport_ = 0;

      protocol_ = "";

      mountpoint_ = "";

      isSuperuser_ = false;

      anonymous_ = false;

      cn_ = "";

      dn_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ClientInfo_descriptor;
    }

    @Override
    public io.emqx.exhook.ClientInfo getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public io.emqx.exhook.ClientInfo build() {
      io.emqx.exhook.ClientInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public io.emqx.exhook.ClientInfo buildPartial() {
      io.emqx.exhook.ClientInfo result = new io.emqx.exhook.ClientInfo(this);
      result.node_ = node_;
      result.clientid_ = clientid_;
      result.username_ = username_;
      result.password_ = password_;
      result.peerhost_ = peerhost_;
      result.sockport_ = sockport_;
      result.protocol_ = protocol_;
      result.mountpoint_ = mountpoint_;
      result.isSuperuser_ = isSuperuser_;
      result.anonymous_ = anonymous_;
      result.cn_ = cn_;
      result.dn_ = dn_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.emqx.exhook.ClientInfo) {
        return mergeFrom((io.emqx.exhook.ClientInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.emqx.exhook.ClientInfo other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getNode().isEmpty()) {
        node_ = other.node_;
        onChanged();
      }
      if (!other.getClientid().isEmpty()) {
        clientid_ = other.clientid_;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getPeerhost().isEmpty()) {
        peerhost_ = other.peerhost_;
        onChanged();
      }
      if (other.getSockport() != 0) {
        setSockport(other.getSockport());
      }
      if (!other.getProtocol().isEmpty()) {
        protocol_ = other.protocol_;
        onChanged();
      }
      if (!other.getMountpoint().isEmpty()) {
        mountpoint_ = other.mountpoint_;
        onChanged();
      }
      if (other.getIsSuperuser() != false) {
        setIsSuperuser(other.getIsSuperuser());
      }
      if (other.getAnonymous() != false) {
        setAnonymous(other.getAnonymous());
      }
      if (!other.getCn().isEmpty()) {
        cn_ = other.cn_;
        onChanged();
      }
      if (!other.getDn().isEmpty()) {
        dn_ = other.dn_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              node_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              clientid_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              username_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              password_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              peerhost_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 48: {
              sockport_ = input.readUInt32();

              break;
            } // case 48
            case 58: {
              protocol_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 66: {
              mountpoint_ = input.readStringRequireUtf8();

              break;
            } // case 66
            case 72: {
              isSuperuser_ = input.readBool();

              break;
            } // case 72
            case 80: {
              anonymous_ = input.readBool();

              break;
            } // case 80
            case 90: {
              cn_ = input.readStringRequireUtf8();

              break;
            } // case 90
            case 98: {
              dn_ = input.readStringRequireUtf8();

              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private Object node_ = "";
    /**
     * <code>string node = 1;</code>
     * @return The node.
     */
    public String getNode() {
      Object ref = node_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        node_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string node = 1;</code>
     * @return The bytes for node.
     */
    public com.google.protobuf.ByteString
        getNodeBytes() {
      Object ref = node_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string node = 1;</code>
     * @param value The node to set.
     * @return This builder for chaining.
     */
    public Builder setNode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      node_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string node = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNode() {
      
      node_ = getDefaultInstance().getNode();
      onChanged();
      return this;
    }
    /**
     * <code>string node = 1;</code>
     * @param value The bytes for node to set.
     * @return This builder for chaining.
     */
    public Builder setNodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      node_ = value;
      onChanged();
      return this;
    }

    private Object clientid_ = "";
    /**
     * <code>string clientid = 2;</code>
     * @return The clientid.
     */
    public String getClientid() {
      Object ref = clientid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string clientid = 2;</code>
     * @return The bytes for clientid.
     */
    public com.google.protobuf.ByteString
        getClientidBytes() {
      Object ref = clientid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientid = 2;</code>
     * @param value The clientid to set.
     * @return This builder for chaining.
     */
    public Builder setClientid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientid() {
      
      clientid_ = getDefaultInstance().getClientid();
      onChanged();
      return this;
    }
    /**
     * <code>string clientid = 2;</code>
     * @param value The bytes for clientid to set.
     * @return This builder for chaining.
     */
    public Builder setClientidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientid_ = value;
      onChanged();
      return this;
    }

    private Object username_ = "";
    /**
     * <code>string username = 3;</code>
     * @return The username.
     */
    public String getUsername() {
      Object ref = username_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string username = 3;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 3;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 3;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private Object password_ = "";
    /**
     * <code>string password = 4;</code>
     * @return The password.
     */
    public String getPassword() {
      Object ref = password_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string password = 4;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 4;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 4;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private Object peerhost_ = "";
    /**
     * <code>string peerhost = 5;</code>
     * @return The peerhost.
     */
    public String getPeerhost() {
      Object ref = peerhost_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        peerhost_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string peerhost = 5;</code>
     * @return The bytes for peerhost.
     */
    public com.google.protobuf.ByteString
        getPeerhostBytes() {
      Object ref = peerhost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        peerhost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string peerhost = 5;</code>
     * @param value The peerhost to set.
     * @return This builder for chaining.
     */
    public Builder setPeerhost(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      peerhost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string peerhost = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeerhost() {
      
      peerhost_ = getDefaultInstance().getPeerhost();
      onChanged();
      return this;
    }
    /**
     * <code>string peerhost = 5;</code>
     * @param value The bytes for peerhost to set.
     * @return This builder for chaining.
     */
    public Builder setPeerhostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      peerhost_ = value;
      onChanged();
      return this;
    }

    private int sockport_ ;
    /**
     * <code>uint32 sockport = 6;</code>
     * @return The sockport.
     */
    @Override
    public int getSockport() {
      return sockport_;
    }
    /**
     * <code>uint32 sockport = 6;</code>
     * @param value The sockport to set.
     * @return This builder for chaining.
     */
    public Builder setSockport(int value) {
      
      sockport_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 sockport = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSockport() {
      
      sockport_ = 0;
      onChanged();
      return this;
    }

    private Object protocol_ = "";
    /**
     * <code>string protocol = 7;</code>
     * @return The protocol.
     */
    public String getProtocol() {
      Object ref = protocol_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string protocol = 7;</code>
     * @return The bytes for protocol.
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string protocol = 7;</code>
     * @param value The protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocol(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string protocol = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      
      protocol_ = getDefaultInstance().getProtocol();
      onChanged();
      return this;
    }
    /**
     * <code>string protocol = 7;</code>
     * @param value The bytes for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protocol_ = value;
      onChanged();
      return this;
    }

    private Object mountpoint_ = "";
    /**
     * <code>string mountpoint = 8;</code>
     * @return The mountpoint.
     */
    public String getMountpoint() {
      Object ref = mountpoint_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mountpoint_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string mountpoint = 8;</code>
     * @return The bytes for mountpoint.
     */
    public com.google.protobuf.ByteString
        getMountpointBytes() {
      Object ref = mountpoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mountpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mountpoint = 8;</code>
     * @param value The mountpoint to set.
     * @return This builder for chaining.
     */
    public Builder setMountpoint(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mountpoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mountpoint = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMountpoint() {
      
      mountpoint_ = getDefaultInstance().getMountpoint();
      onChanged();
      return this;
    }
    /**
     * <code>string mountpoint = 8;</code>
     * @param value The bytes for mountpoint to set.
     * @return This builder for chaining.
     */
    public Builder setMountpointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mountpoint_ = value;
      onChanged();
      return this;
    }

    private boolean isSuperuser_ ;
    /**
     * <code>bool is_superuser = 9;</code>
     * @return The isSuperuser.
     */
    @Override
    public boolean getIsSuperuser() {
      return isSuperuser_;
    }
    /**
     * <code>bool is_superuser = 9;</code>
     * @param value The isSuperuser to set.
     * @return This builder for chaining.
     */
    public Builder setIsSuperuser(boolean value) {
      
      isSuperuser_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_superuser = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSuperuser() {
      
      isSuperuser_ = false;
      onChanged();
      return this;
    }

    private boolean anonymous_ ;
    /**
     * <code>bool anonymous = 10;</code>
     * @return The anonymous.
     */
    @Override
    public boolean getAnonymous() {
      return anonymous_;
    }
    /**
     * <code>bool anonymous = 10;</code>
     * @param value The anonymous to set.
     * @return This builder for chaining.
     */
    public Builder setAnonymous(boolean value) {
      
      anonymous_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool anonymous = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnonymous() {
      
      anonymous_ = false;
      onChanged();
      return this;
    }

    private Object cn_ = "";
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @return The cn.
     */
    public String getCn() {
      Object ref = cn_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cn_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @return The bytes for cn.
     */
    public com.google.protobuf.ByteString
        getCnBytes() {
      Object ref = cn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @param value The cn to set.
     * @return This builder for chaining.
     */
    public Builder setCn(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearCn() {
      
      cn_ = getDefaultInstance().getCn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * common name of client TLS cert
     * </pre>
     *
     * <code>string cn = 11;</code>
     * @param value The bytes for cn to set.
     * @return This builder for chaining.
     */
    public Builder setCnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cn_ = value;
      onChanged();
      return this;
    }

    private Object dn_ = "";
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @return The dn.
     */
    public String getDn() {
      Object ref = dn_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dn_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @return The bytes for dn.
     */
    public com.google.protobuf.ByteString
        getDnBytes() {
      Object ref = dn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @param value The dn to set.
     * @return This builder for chaining.
     */
    public Builder setDn(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearDn() {
      
      dn_ = getDefaultInstance().getDn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * subject of client TLS cert
     * </pre>
     *
     * <code>string dn = 12;</code>
     * @param value The bytes for dn to set.
     * @return This builder for chaining.
     */
    public Builder setDnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dn_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v2.ClientInfo)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v2.ClientInfo)
  private static final io.emqx.exhook.ClientInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.emqx.exhook.ClientInfo();
  }

  public static io.emqx.exhook.ClientInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientInfo>
      PARSER = new com.google.protobuf.AbstractParser<ClientInfo>() {
    @Override
    public ClientInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ClientInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public io.emqx.exhook.ClientInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

