// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

/**
 * Protobuf type {@code emqx.exhook.v2.ConnInfo}
 */
public final class ConnInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v2.ConnInfo)
        ConnInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConnInfo.newBuilder() to construct.
  private ConnInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConnInfo() {
    node_ = "";
    clientid_ = "";
    username_ = "";
    peerhost_ = "";
    protoName_ = "";
    protoVer_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConnInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ConnInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ConnInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.emqx.exhook.ConnInfo.class, io.emqx.exhook.ConnInfo.Builder.class);
  }

  public static final int NODE_FIELD_NUMBER = 1;
  private volatile Object node_;
  /**
   * <code>string node = 1;</code>
   * @return The node.
   */
  @Override
  public String getNode() {
    Object ref = node_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      node_ = s;
      return s;
    }
  }
  /**
   * <code>string node = 1;</code>
   * @return The bytes for node.
   */
  @Override
  public com.google.protobuf.ByteString
      getNodeBytes() {
    Object ref = node_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      node_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private volatile Object clientid_;
  /**
   * <code>string clientid = 2;</code>
   * @return The clientid.
   */
  @Override
  public String getClientid() {
    Object ref = clientid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      clientid_ = s;
      return s;
    }
  }
  /**
   * <code>string clientid = 2;</code>
   * @return The bytes for clientid.
   */
  @Override
  public com.google.protobuf.ByteString
      getClientidBytes() {
    Object ref = clientid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      clientid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 3;
  private volatile Object username_;
  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  @Override
  public String getUsername() {
    Object ref = username_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  @Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    Object ref = username_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEERHOST_FIELD_NUMBER = 4;
  private volatile Object peerhost_;
  /**
   * <code>string peerhost = 4;</code>
   * @return The peerhost.
   */
  @Override
  public String getPeerhost() {
    Object ref = peerhost_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      peerhost_ = s;
      return s;
    }
  }
  /**
   * <code>string peerhost = 4;</code>
   * @return The bytes for peerhost.
   */
  @Override
  public com.google.protobuf.ByteString
      getPeerhostBytes() {
    Object ref = peerhost_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      peerhost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOCKPORT_FIELD_NUMBER = 5;
  private int sockport_;
  /**
   * <code>uint32 sockport = 5;</code>
   * @return The sockport.
   */
  @Override
  public int getSockport() {
    return sockport_;
  }

  public static final int PROTO_NAME_FIELD_NUMBER = 6;
  private volatile Object protoName_;
  /**
   * <code>string proto_name = 6;</code>
   * @return The protoName.
   */
  @Override
  public String getProtoName() {
    Object ref = protoName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      protoName_ = s;
      return s;
    }
  }
  /**
   * <code>string proto_name = 6;</code>
   * @return The bytes for protoName.
   */
  @Override
  public com.google.protobuf.ByteString
      getProtoNameBytes() {
    Object ref = protoName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      protoName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTO_VER_FIELD_NUMBER = 7;
  private volatile Object protoVer_;
  /**
   * <code>string proto_ver = 7;</code>
   * @return The protoVer.
   */
  @Override
  public String getProtoVer() {
    Object ref = protoVer_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      protoVer_ = s;
      return s;
    }
  }
  /**
   * <code>string proto_ver = 7;</code>
   * @return The bytes for protoVer.
   */
  @Override
  public com.google.protobuf.ByteString
      getProtoVerBytes() {
    Object ref = protoVer_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      protoVer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEEPALIVE_FIELD_NUMBER = 8;
  private int keepalive_;
  /**
   * <code>uint32 keepalive = 8;</code>
   * @return The keepalive.
   */
  @Override
  public int getKeepalive() {
    return keepalive_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(node_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, node_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerhost_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, peerhost_);
    }
    if (sockport_ != 0) {
      output.writeUInt32(5, sockport_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protoName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, protoName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protoVer_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, protoVer_);
    }
    if (keepalive_ != 0) {
      output.writeUInt32(8, keepalive_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(node_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, node_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerhost_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, peerhost_);
    }
    if (sockport_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, sockport_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protoName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, protoName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protoVer_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, protoVer_);
    }
    if (keepalive_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, keepalive_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.emqx.exhook.ConnInfo)) {
      return super.equals(obj);
    }
    io.emqx.exhook.ConnInfo other = (io.emqx.exhook.ConnInfo) obj;

    if (!getNode()
        .equals(other.getNode())) return false;
    if (!getClientid()
        .equals(other.getClientid())) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPeerhost()
        .equals(other.getPeerhost())) return false;
    if (getSockport()
        != other.getSockport()) return false;
    if (!getProtoName()
        .equals(other.getProtoName())) return false;
    if (!getProtoVer()
        .equals(other.getProtoVer())) return false;
    if (getKeepalive()
        != other.getKeepalive()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODE_FIELD_NUMBER;
    hash = (53 * hash) + getNode().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientid().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PEERHOST_FIELD_NUMBER;
    hash = (53 * hash) + getPeerhost().hashCode();
    hash = (37 * hash) + SOCKPORT_FIELD_NUMBER;
    hash = (53 * hash) + getSockport();
    hash = (37 * hash) + PROTO_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProtoName().hashCode();
    hash = (37 * hash) + PROTO_VER_FIELD_NUMBER;
    hash = (53 * hash) + getProtoVer().hashCode();
    hash = (37 * hash) + KEEPALIVE_FIELD_NUMBER;
    hash = (53 * hash) + getKeepalive();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.emqx.exhook.ConnInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ConnInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ConnInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ConnInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.emqx.exhook.ConnInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v2.ConnInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v2.ConnInfo)
      ConnInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ConnInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ConnInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.emqx.exhook.ConnInfo.class, io.emqx.exhook.ConnInfo.Builder.class);
    }

    // Construct using io.emqx.exhook.ConnInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      node_ = "";

      clientid_ = "";

      username_ = "";

      peerhost_ = "";

      sockport_ = 0;

      protoName_ = "";

      protoVer_ = "";

      keepalive_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_ConnInfo_descriptor;
    }

    @Override
    public io.emqx.exhook.ConnInfo getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public io.emqx.exhook.ConnInfo build() {
      io.emqx.exhook.ConnInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public io.emqx.exhook.ConnInfo buildPartial() {
      io.emqx.exhook.ConnInfo result = new io.emqx.exhook.ConnInfo(this);
      result.node_ = node_;
      result.clientid_ = clientid_;
      result.username_ = username_;
      result.peerhost_ = peerhost_;
      result.sockport_ = sockport_;
      result.protoName_ = protoName_;
      result.protoVer_ = protoVer_;
      result.keepalive_ = keepalive_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.emqx.exhook.ConnInfo) {
        return mergeFrom((io.emqx.exhook.ConnInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.emqx.exhook.ConnInfo other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getNode().isEmpty()) {
        node_ = other.node_;
        onChanged();
      }
      if (!other.getClientid().isEmpty()) {
        clientid_ = other.clientid_;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPeerhost().isEmpty()) {
        peerhost_ = other.peerhost_;
        onChanged();
      }
      if (other.getSockport() != 0) {
        setSockport(other.getSockport());
      }
      if (!other.getProtoName().isEmpty()) {
        protoName_ = other.protoName_;
        onChanged();
      }
      if (!other.getProtoVer().isEmpty()) {
        protoVer_ = other.protoVer_;
        onChanged();
      }
      if (other.getKeepalive() != 0) {
        setKeepalive(other.getKeepalive());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              node_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              clientid_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              username_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              peerhost_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 40: {
              sockport_ = input.readUInt32();

              break;
            } // case 40
            case 50: {
              protoName_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              protoVer_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 64: {
              keepalive_ = input.readUInt32();

              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private Object node_ = "";
    /**
     * <code>string node = 1;</code>
     * @return The node.
     */
    public String getNode() {
      Object ref = node_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        node_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string node = 1;</code>
     * @return The bytes for node.
     */
    public com.google.protobuf.ByteString
        getNodeBytes() {
      Object ref = node_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string node = 1;</code>
     * @param value The node to set.
     * @return This builder for chaining.
     */
    public Builder setNode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      node_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string node = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNode() {
      
      node_ = getDefaultInstance().getNode();
      onChanged();
      return this;
    }
    /**
     * <code>string node = 1;</code>
     * @param value The bytes for node to set.
     * @return This builder for chaining.
     */
    public Builder setNodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      node_ = value;
      onChanged();
      return this;
    }

    private Object clientid_ = "";
    /**
     * <code>string clientid = 2;</code>
     * @return The clientid.
     */
    public String getClientid() {
      Object ref = clientid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string clientid = 2;</code>
     * @return The bytes for clientid.
     */
    public com.google.protobuf.ByteString
        getClientidBytes() {
      Object ref = clientid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientid = 2;</code>
     * @param value The clientid to set.
     * @return This builder for chaining.
     */
    public Builder setClientid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientid() {
      
      clientid_ = getDefaultInstance().getClientid();
      onChanged();
      return this;
    }
    /**
     * <code>string clientid = 2;</code>
     * @param value The bytes for clientid to set.
     * @return This builder for chaining.
     */
    public Builder setClientidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientid_ = value;
      onChanged();
      return this;
    }

    private Object username_ = "";
    /**
     * <code>string username = 3;</code>
     * @return The username.
     */
    public String getUsername() {
      Object ref = username_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string username = 3;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 3;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 3;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private Object peerhost_ = "";
    /**
     * <code>string peerhost = 4;</code>
     * @return The peerhost.
     */
    public String getPeerhost() {
      Object ref = peerhost_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        peerhost_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string peerhost = 4;</code>
     * @return The bytes for peerhost.
     */
    public com.google.protobuf.ByteString
        getPeerhostBytes() {
      Object ref = peerhost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        peerhost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string peerhost = 4;</code>
     * @param value The peerhost to set.
     * @return This builder for chaining.
     */
    public Builder setPeerhost(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      peerhost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string peerhost = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeerhost() {
      
      peerhost_ = getDefaultInstance().getPeerhost();
      onChanged();
      return this;
    }
    /**
     * <code>string peerhost = 4;</code>
     * @param value The bytes for peerhost to set.
     * @return This builder for chaining.
     */
    public Builder setPeerhostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      peerhost_ = value;
      onChanged();
      return this;
    }

    private int sockport_ ;
    /**
     * <code>uint32 sockport = 5;</code>
     * @return The sockport.
     */
    @Override
    public int getSockport() {
      return sockport_;
    }
    /**
     * <code>uint32 sockport = 5;</code>
     * @param value The sockport to set.
     * @return This builder for chaining.
     */
    public Builder setSockport(int value) {
      
      sockport_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 sockport = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSockport() {
      
      sockport_ = 0;
      onChanged();
      return this;
    }

    private Object protoName_ = "";
    /**
     * <code>string proto_name = 6;</code>
     * @return The protoName.
     */
    public String getProtoName() {
      Object ref = protoName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        protoName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string proto_name = 6;</code>
     * @return The bytes for protoName.
     */
    public com.google.protobuf.ByteString
        getProtoNameBytes() {
      Object ref = protoName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        protoName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proto_name = 6;</code>
     * @param value The protoName to set.
     * @return This builder for chaining.
     */
    public Builder setProtoName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protoName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proto_name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtoName() {
      
      protoName_ = getDefaultInstance().getProtoName();
      onChanged();
      return this;
    }
    /**
     * <code>string proto_name = 6;</code>
     * @param value The bytes for protoName to set.
     * @return This builder for chaining.
     */
    public Builder setProtoNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protoName_ = value;
      onChanged();
      return this;
    }

    private Object protoVer_ = "";
    /**
     * <code>string proto_ver = 7;</code>
     * @return The protoVer.
     */
    public String getProtoVer() {
      Object ref = protoVer_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        protoVer_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string proto_ver = 7;</code>
     * @return The bytes for protoVer.
     */
    public com.google.protobuf.ByteString
        getProtoVerBytes() {
      Object ref = protoVer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        protoVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proto_ver = 7;</code>
     * @param value The protoVer to set.
     * @return This builder for chaining.
     */
    public Builder setProtoVer(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protoVer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proto_ver = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtoVer() {
      
      protoVer_ = getDefaultInstance().getProtoVer();
      onChanged();
      return this;
    }
    /**
     * <code>string proto_ver = 7;</code>
     * @param value The bytes for protoVer to set.
     * @return This builder for chaining.
     */
    public Builder setProtoVerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protoVer_ = value;
      onChanged();
      return this;
    }

    private int keepalive_ ;
    /**
     * <code>uint32 keepalive = 8;</code>
     * @return The keepalive.
     */
    @Override
    public int getKeepalive() {
      return keepalive_;
    }
    /**
     * <code>uint32 keepalive = 8;</code>
     * @param value The keepalive to set.
     * @return This builder for chaining.
     */
    public Builder setKeepalive(int value) {
      
      keepalive_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 keepalive = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeepalive() {
      
      keepalive_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v2.ConnInfo)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v2.ConnInfo)
  private static final io.emqx.exhook.ConnInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.emqx.exhook.ConnInfo();
  }

  public static io.emqx.exhook.ConnInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConnInfo>
      PARSER = new com.google.protobuf.AbstractParser<ConnInfo>() {
    @Override
    public ConnInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConnInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ConnInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public io.emqx.exhook.ConnInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

