// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

/**
 * Protobuf type {@code emqx.exhook.v2.LoadedResponse}
 */
public final class LoadedResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v2.LoadedResponse)
        LoadedResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LoadedResponse.newBuilder() to construct.
  private LoadedResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoadedResponse() {
    hooks_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new LoadedResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_LoadedResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_LoadedResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.emqx.exhook.LoadedResponse.class, io.emqx.exhook.LoadedResponse.Builder.class);
  }

  public static final int HOOKS_FIELD_NUMBER = 1;
  private java.util.List<io.emqx.exhook.HookSpec> hooks_;
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  @Override
  public java.util.List<io.emqx.exhook.HookSpec> getHooksList() {
    return hooks_;
  }
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  @Override
  public java.util.List<? extends io.emqx.exhook.HookSpecOrBuilder> 
      getHooksOrBuilderList() {
    return hooks_;
  }
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  @Override
  public int getHooksCount() {
    return hooks_.size();
  }
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  @Override
  public io.emqx.exhook.HookSpec getHooks(int index) {
    return hooks_.get(index);
  }
  /**
   * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
   */
  @Override
  public io.emqx.exhook.HookSpecOrBuilder getHooksOrBuilder(
      int index) {
    return hooks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < hooks_.size(); i++) {
      output.writeMessage(1, hooks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < hooks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, hooks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.emqx.exhook.LoadedResponse)) {
      return super.equals(obj);
    }
    io.emqx.exhook.LoadedResponse other = (io.emqx.exhook.LoadedResponse) obj;

    if (!getHooksList()
        .equals(other.getHooksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHooksCount() > 0) {
      hash = (37 * hash) + HOOKS_FIELD_NUMBER;
      hash = (53 * hash) + getHooksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.emqx.exhook.LoadedResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.LoadedResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.LoadedResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.LoadedResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.emqx.exhook.LoadedResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v2.LoadedResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v2.LoadedResponse)
      LoadedResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_LoadedResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_LoadedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.emqx.exhook.LoadedResponse.class, io.emqx.exhook.LoadedResponse.Builder.class);
    }

    // Construct using io.emqx.exhook.LoadedResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      if (hooksBuilder_ == null) {
        hooks_ = java.util.Collections.emptyList();
      } else {
        hooks_ = null;
        hooksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v2_LoadedResponse_descriptor;
    }

    @Override
    public io.emqx.exhook.LoadedResponse getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public io.emqx.exhook.LoadedResponse build() {
      io.emqx.exhook.LoadedResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public io.emqx.exhook.LoadedResponse buildPartial() {
      io.emqx.exhook.LoadedResponse result = new io.emqx.exhook.LoadedResponse(this);
      int from_bitField0_ = bitField0_;
      if (hooksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          hooks_ = java.util.Collections.unmodifiableList(hooks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.hooks_ = hooks_;
      } else {
        result.hooks_ = hooksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.emqx.exhook.LoadedResponse) {
        return mergeFrom((io.emqx.exhook.LoadedResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.emqx.exhook.LoadedResponse other) {
      if (other == getDefaultInstance()) return this;
      if (hooksBuilder_ == null) {
        if (!other.hooks_.isEmpty()) {
          if (hooks_.isEmpty()) {
            hooks_ = other.hooks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHooksIsMutable();
            hooks_.addAll(other.hooks_);
          }
          onChanged();
        }
      } else {
        if (!other.hooks_.isEmpty()) {
          if (hooksBuilder_.isEmpty()) {
            hooksBuilder_.dispose();
            hooksBuilder_ = null;
            hooks_ = other.hooks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            hooksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHooksFieldBuilder() : null;
          } else {
            hooksBuilder_.addAllMessages(other.hooks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.emqx.exhook.HookSpec m =
                  input.readMessage(
                      io.emqx.exhook.HookSpec.parser(),
                      extensionRegistry);
              if (hooksBuilder_ == null) {
                ensureHooksIsMutable();
                hooks_.add(m);
              } else {
                hooksBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.emqx.exhook.HookSpec> hooks_ =
      java.util.Collections.emptyList();
    private void ensureHooksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        hooks_ = new java.util.ArrayList<io.emqx.exhook.HookSpec>(hooks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.HookSpec, io.emqx.exhook.HookSpec.Builder, io.emqx.exhook.HookSpecOrBuilder> hooksBuilder_;

    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public java.util.List<io.emqx.exhook.HookSpec> getHooksList() {
      if (hooksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(hooks_);
      } else {
        return hooksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public int getHooksCount() {
      if (hooksBuilder_ == null) {
        return hooks_.size();
      } else {
        return hooksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public io.emqx.exhook.HookSpec getHooks(int index) {
      if (hooksBuilder_ == null) {
        return hooks_.get(index);
      } else {
        return hooksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder setHooks(
        int index, io.emqx.exhook.HookSpec value) {
      if (hooksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHooksIsMutable();
        hooks_.set(index, value);
        onChanged();
      } else {
        hooksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder setHooks(
        int index, io.emqx.exhook.HookSpec.Builder builderForValue) {
      if (hooksBuilder_ == null) {
        ensureHooksIsMutable();
        hooks_.set(index, builderForValue.build());
        onChanged();
      } else {
        hooksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder addHooks(io.emqx.exhook.HookSpec value) {
      if (hooksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHooksIsMutable();
        hooks_.add(value);
        onChanged();
      } else {
        hooksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder addHooks(
        int index, io.emqx.exhook.HookSpec value) {
      if (hooksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHooksIsMutable();
        hooks_.add(index, value);
        onChanged();
      } else {
        hooksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder addHooks(
        io.emqx.exhook.HookSpec.Builder builderForValue) {
      if (hooksBuilder_ == null) {
        ensureHooksIsMutable();
        hooks_.add(builderForValue.build());
        onChanged();
      } else {
        hooksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder addHooks(
        int index, io.emqx.exhook.HookSpec.Builder builderForValue) {
      if (hooksBuilder_ == null) {
        ensureHooksIsMutable();
        hooks_.add(index, builderForValue.build());
        onChanged();
      } else {
        hooksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder addAllHooks(
        Iterable<? extends io.emqx.exhook.HookSpec> values) {
      if (hooksBuilder_ == null) {
        ensureHooksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hooks_);
        onChanged();
      } else {
        hooksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder clearHooks() {
      if (hooksBuilder_ == null) {
        hooks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        hooksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public Builder removeHooks(int index) {
      if (hooksBuilder_ == null) {
        ensureHooksIsMutable();
        hooks_.remove(index);
        onChanged();
      } else {
        hooksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public io.emqx.exhook.HookSpec.Builder getHooksBuilder(
        int index) {
      return getHooksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public io.emqx.exhook.HookSpecOrBuilder getHooksOrBuilder(
        int index) {
      if (hooksBuilder_ == null) {
        return hooks_.get(index);  } else {
        return hooksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public java.util.List<? extends io.emqx.exhook.HookSpecOrBuilder> 
         getHooksOrBuilderList() {
      if (hooksBuilder_ != null) {
        return hooksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(hooks_);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public io.emqx.exhook.HookSpec.Builder addHooksBuilder() {
      return getHooksFieldBuilder().addBuilder(
          io.emqx.exhook.HookSpec.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public io.emqx.exhook.HookSpec.Builder addHooksBuilder(
        int index) {
      return getHooksFieldBuilder().addBuilder(
          index, io.emqx.exhook.HookSpec.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v2.HookSpec hooks = 1;</code>
     */
    public java.util.List<io.emqx.exhook.HookSpec.Builder> 
         getHooksBuilderList() {
      return getHooksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.HookSpec, io.emqx.exhook.HookSpec.Builder, io.emqx.exhook.HookSpecOrBuilder> 
        getHooksFieldBuilder() {
      if (hooksBuilder_ == null) {
        hooksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.emqx.exhook.HookSpec, io.emqx.exhook.HookSpec.Builder, io.emqx.exhook.HookSpecOrBuilder>(
                hooks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        hooks_ = null;
      }
      return hooksBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v2.LoadedResponse)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v2.LoadedResponse)
  private static final io.emqx.exhook.LoadedResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.emqx.exhook.LoadedResponse();
  }

  public static io.emqx.exhook.LoadedResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoadedResponse>
      PARSER = new com.google.protobuf.AbstractParser<LoadedResponse>() {
    @Override
    public LoadedResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LoadedResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LoadedResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public io.emqx.exhook.LoadedResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

